"""Orchestrates storage operations across the registered strategies.

The orchestrator is the single entry point for persisting or deleting
chunks and their embeddings. Strategies must never be invoked directly by
calling code -- "always go through the orchestrator" is a project-wide
rule, notably so that cross-strategy concerns (chunk/embedding alignment,
Qdrant-then-MySQL status propagation, partial-failure policy) live in one
place instead of being duplicated or forgotten.
"""
from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from app.exceptions import PartialStorageError, StorageAlignmentError, StorageError
from app.models.chunk import Chunk
from app.models.embedding import Embedding
from .base import StorageOutcome, StorageReport
from .registry import StorageRegistry


def _logical_chunk_id(chunk: Chunk) -> str:
    """Return the logical identifier used to align a chunk with its embedding.

    Mirrors the fallback rule applied by ``SentenceTransformerEmbedding``
    (see EMBEDDING.md, section 7): when a chunker does not set
    ``chunk.chunk_id`` -- which is the case for ``RecursiveChunker``, whose
    chunks always carry ``chunk_id=None`` -- the logical identifier used
    downstream falls back to ``f"{source_name}:{chunk_index}"``.

    ``Embedding.chunk_id`` already applies this exact fallback when it is
    created, so reconstructing it here on the chunk side (instead of
    comparing the raw, possibly ``None``, ``chunk.chunk_id`` field) is what
    makes the alignment check correct for every chunker, not only for
    chunkers that explicitly set ``chunk_id``.
    """
    return chunk.chunk_id or f"{chunk.source_name}:{chunk.chunk_index}"


class StorageOrchestrator:
    """Coordinates one or more :class:`~app.storage.base.StorageStrategy`.

    Parameters
    ----------
    registry:
        Registry used to resolve a strategy name to its class.
    strategy_sequence:
        Ordered names of the strategies to run, both for ``save()`` and
        ``delete()``. Defaults to MySQL first, then Qdrant, since Qdrant
        points are keyed on the ``id_chunk`` generated by MySQL.
    stop_on_failure:
        When ``True``, the first strategy failure stops the sequence and
        re-raises the original :class:`~app.exceptions.storage.StorageError`
        instead of being captured into the report.
    raise_on_partial_failure:
        When ``True`` (default), a :class:`~app.exceptions.storage.PartialStorageError`
        is raised at the end of ``save()``/``delete()`` if the resulting
        report has failures but ``stop_on_failure`` was ``False``. The
        failure details include both failing and successful strategy names,
        so callers can still inspect what actually succeeded. Set to
        ``False`` to only ever get a report back, and
        let the calling layer decide whether to raise
        ``PartialStorageError`` itself (for example at the API boundary).
    options:
        Extra keyword arguments forwarded to every strategy constructor
        (for example ``dsn=`` or ``collection_name=``).
    """

    def __init__(
        self,
        registry: StorageRegistry,
        *,
        strategy_sequence: tuple[str, ...] = ("mysql", "qdrant"),
        stop_on_failure: bool = False,
        raise_on_partial_failure: bool = True,
        **options: Any,
    ) -> None:
        self.registry = registry
        self.strategy_sequence = strategy_sequence
        self.stop_on_failure = stop_on_failure
        self.raise_on_partial_failure = raise_on_partial_failure
        self.options = options

    def save(
        self,
        chunks: Sequence[Chunk],
        embeddings: Sequence[Embedding],
    ) -> StorageReport:
        """Persist ``chunks``/``embeddings`` through every configured strategy.

        After a successful Qdrant outcome, the corresponding MySQL rows are
        marked as indexed via :meth:`_mark_indexed_after_qdrant`, so that
        ``QdrantStorage`` itself never has to know about the MySQL schema.
        """
        self._check_alignment(chunks, embeddings)
        outcomes: list[StorageOutcome] = []
        for name in self.strategy_sequence:
            outcome = self._run(name, "save", chunks, embeddings)
            outcomes.append(outcome)
            if name == "qdrant" and outcome.success:
                self._mark_indexed_after_qdrant(chunks)
            if self.stop_on_failure and not outcome.success:
                break
        report = StorageReport(tuple(outcomes))
        self._maybe_raise_partial(report)
        return report

    def delete(self, chunk_ids: Sequence[Any]) -> StorageReport:
        """Delete the storage records identified by ``chunk_ids``.

        Runs every strategy in :attr:`strategy_sequence`, applying the same
        ``stop_on_failure`` policy as :meth:`save`, and returns a
        :class:`~app.storage.base.StorageReport` built the same way.
        """
        outcomes: list[StorageOutcome] = []
        for name in self.strategy_sequence:
            outcome = self._run(name, "delete", chunk_ids)
            outcomes.append(outcome)
            if self.stop_on_failure and not outcome.success:
                break
        report = StorageReport(tuple(outcomes))
        self._maybe_raise_partial(report)
        return report

    def _run(self, strategy_name: str, method_name: str, *args: Any) -> StorageOutcome:
        """Resolve, instantiate and run one strategy, capturing failures."""
        try:
            strategy = self.registry.get(strategy_name)(**self.options)
            method = getattr(strategy, method_name)
            return method(*args)
        except StorageError as exc:
            if self.stop_on_failure:
                raise
            return StorageOutcome(strategy_name, failures=(self._as_failure(exc),))

    @staticmethod
    def _as_failure(exc: StorageError) -> dict[str, Any]:
        """Convert a captured :class:`StorageError` into a failure record.

        Uses ``exc.to_dict()`` when available so the original ``message``,
        ``error_code`` and ``details`` survive into the report, instead of
        being replaced by a generic placeholder.
        """
        to_dict = getattr(exc, "to_dict", None)
        if callable(to_dict):
            return to_dict()
        return {"message": str(exc), "error_code": "STORAGE_ERROR"}

    def _mark_indexed_after_qdrant(self, chunks: Sequence[Chunk]) -> None:
        """Mark the given chunks as indexed in MySQL after a Qdrant success.

        This replaces the previous design where ``QdrantStorage.save()``
        opened its own SQLAlchemy connection to update ``chunk_rag``
        directly. That cross-strategy write now lives here, and is
        delegated to ``MySQLStorage.mark_indexed()`` so that
        ``QdrantStorage`` no longer needs to import ``sqlalchemy`` or know
        anything about the MySQL schema.
        """
        if not self.registry.has("mysql"):
            return
        chunk_ids = tuple(
            chunk.metadata.get("id_chunk")
            for chunk in chunks
            if chunk.metadata.get("id_chunk") is not None
        )
        if not chunk_ids:
            return
        mysql_strategy = self.registry.get("mysql")(**self.options)
        mark_indexed = getattr(mysql_strategy, "mark_indexed", None)
        if callable(mark_indexed):
            mark_indexed(chunk_ids)

    def _check_alignment(
        self,
        chunks: Sequence[Chunk],
        embeddings: Sequence[Embedding],
    ) -> None:
        """Validate that ``chunks`` and ``embeddings`` describe the same batch."""
        if len(chunks) != len(embeddings):
            raise StorageAlignmentError(
                chunk_count=len(chunks),
                embedding_count=len(embeddings),
            )
        pairs = zip(chunks, embeddings, strict=True)
        for index, (chunk, embedding) in enumerate(pairs):
            expected_id = _logical_chunk_id(chunk)
            if expected_id != embedding.chunk_id:
                raise StorageAlignmentError(
                    details={
                        "index": index,
                        "chunk_id": expected_id,
                        "embedding_chunk_id": embedding.chunk_id,
                    }
                )

    def _maybe_raise_partial(self, report: StorageReport) -> None:
        """Raise :class:`PartialStorageError` for a report with failures.

        Only triggers when the sequence was allowed to run to completion
        (``stop_on_failure=False``, otherwise the original error already
        propagated from :meth:`_run`) and when the orchestrator is
        configured to be noisy about partial failures
        (``raise_on_partial_failure=True``, the default).
        """
        if not report.has_failures:
            return
        if self.stop_on_failure or not self.raise_on_partial_failure:
            return
        raise PartialStorageError(
            details={
                "failures": list(report.failures),
                "succeeded_strategies": [
                    outcome.strategy_name
                    for outcome in report.outcomes
                    if outcome.success
                ],
            }
        )
