"""Ingestion endpoints — file, files, database.

These endpoints expose the full ingestion pipeline (load → parse →
chunk → embed → store) as HTTP APIs.
"""
from __future__ import annotations

import logging
import os
import tempfile
import time
from typing import Annotated

from dotenv import load_dotenv
from fastapi import APIRouter, Depends, UploadFile, File
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError

from app.api.auth import verify_api_key
from app.api.deps import (
    get_chunker_orchestrator,
    get_data_source_orchestrator,
    get_embedding_orchestrator,
    get_parser_orchestrator,
    get_storage_orchestrator,
)
from app.api.schemas import (
    IngestDatabaseRequest,
    IngestFileRequest,
    IngestMultipleRequest,
    IngestResponse,
    IngestResult,
)

logger = logging.getLogger("gmao_rag.api.ingest")

router = APIRouter(prefix="/ingest", tags=["Ingestion"])


# =====================================================================
# MySQL document registration helper
# =====================================================================

# Map file extensions to the document.type_fichier MySQL enum values.
_EXT_TO_TYPE: dict[str, str] = {
    ".pdf": "PDF",
    ".docx": "DOCX",
    ".doc": "DOCX",
    ".txt": "TXT",
    ".html": "HTML",
    ".htm": "HTML",
    ".md": "MD",
}


def _dsn_from_env() -> str | None:
    """Build a MySQL DSN from individual ``GMAO_DB_*`` env vars.

    Mirrors ``MySQLStorage._dsn_from_env`` so that the ingest layer
    does not depend on the storage strategy for basic DB access.
    """
    host = os.getenv("GMAO_DB_HOST")
    user = os.getenv("GMAO_DB_USER")
    database = os.getenv("GMAO_DB_NAME")
    if not all((host, user, database)):
        return None
    password = os.getenv("GMAO_DB_PASSWORD", "")
    port = os.getenv("GMAO_DB_PORT", "3306")
    return f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}"


def _create_document(
    engine: object,
    source_name: str,
    source_path: str | None,
    *,
    id_equipement: int | None = None,
    file_size: int = 0,
) -> int:
    """Insert a ``documents`` row in MySQL and return ``id_document``.

    The storage strategies (MySQL + Qdrant) require every chunk to carry
    ``id_document`` in its metadata.  This function is called once per
    ingested file, right after chunking, so that the IDs can be injected
    into every chunk before the embed → store steps.
    """
    ext = os.path.splitext(source_name)[1].lower() if source_name else ""
    doc_type = _EXT_TO_TYPE.get(ext, "TXT")
    titre = os.path.splitext(source_name)[0] if source_name else "untitled"
    chemin = source_path or source_name

    with engine.begin() as conn:
        result = conn.execute(
            text(
                "INSERT INTO documents "
                "(titre, nom_fichier, type_fichier, chemin_fichier, taille, "
                " id_equipement) "
                "VALUES (:titre, :nom, :type, :chemin, :taille, :equip)"
            ),
            {
                "titre": titre,
                "nom": source_name,
                "type": doc_type,
                "chemin": chemin,
                "taille": file_size,
                "equip": id_equipement,
            },
        )
        return int(result.lastrowid)


# =====================================================================
# Pipeline helper
# =====================================================================

async def _ingest_source(  # noqa: C901 — complex but linear pipeline
    source: object,
    *,
    data_source_orch: object,
    parser_orch: object,
    chunker_orch: object,
    embedding_orch: object,
    storage_orch: object,
    chunk_size: int = 500,
    chunk_overlap: int = 50,
    id_equipement: int | None = None,
) -> IngestResult:
    """Run the full ingestion pipeline: load → parse → chunk → embed → store.

    This is the core function shared by all ingestion endpoints.
    It catches exceptions per-file to allow partial success in batch mode.

    Between chunking and embedding, a ``document`` row is created in MySQL
    and ``id_document`` / ``id_equipement`` are injected into each chunk's
    metadata — this is required by both MySQLStorage and QdrantStorage.
    """
    start = time.perf_counter()
    doc_name = str(source)

    try:
        # --- Step 1: Load ---
        doc = data_source_orch.load(source)

        # --- Step 2: Parse ---
        parsed = parser_orch.parse(doc)

        # --- Step 3: Chunk ---
        chunks = chunker_orch.chunk(parsed)

        # --- Step 3.5: Register document in MySQL + inject IDs ---
        # MySQLStorage requires id_document or id_panne in chunk metadata.
        # QdrantStorage requires id_chunk (generated by MySQLStorage).
        # We create the document row now so that MySQLStorage can link
        # chunks to it during its save() step.
        load_dotenv()
        dsn = os.getenv("MYSQL_DSN") or _dsn_from_env()
        if dsn:
            engine = create_engine(dsn)
            file_size = doc.size if doc.size else 0
            id_document = _create_document(
                engine,
                doc.source_name,
                str(doc.source_path) if doc.source_path else None,
                id_equipement=id_equipement,
                file_size=file_size,
            )
            for chunk in chunks:
                chunk.metadata["id_document"] = id_document
                if id_equipement is not None:
                    chunk.metadata["id_equipement"] = id_equipement

        # --- Step 4: Embed ---
        embeddings = embedding_orch.embed(chunks)

        # --- Step 5: Store ---
        storage_orch.save(chunks, embeddings)

        elapsed = (time.perf_counter() - start) * 1000
        return IngestResult(
            status="ok",
            document_name=doc.source_name,
            chunks_count=len(chunks),
            duration_ms=round(elapsed, 2),
        )

    except Exception as exc:
        elapsed = (time.perf_counter() - start) * 1000
        logger.error("Ingestion failed for %s: %s", doc_name, exc)
        return IngestResult(
            status="error",
            document_name=doc_name,
            chunks_count=0,
            duration_ms=round(elapsed, 2),
            error=str(exc),
        )


# =====================================================================
# POST /api/v1/ingest/file — Single file upload
# =====================================================================

@router.post(
    "/file",
    response_model=IngestResponse,
    summary="Ingest a single file",
    description="Upload a file and run the full ingestion pipeline (load → parse → chunk → embed → store).",
)
async def ingest_file(
    _token: Annotated[str, Depends(verify_api_key)],
    file: UploadFile = File(..., description="File to ingest"),
    id_equipement: int | None = None,
    chunk_size: int = 500,
    chunk_overlap: int = 50,
    data_source_orch = Depends(get_data_source_orchestrator),
    parser_orch = Depends(get_parser_orchestrator),
    chunker_orch = Depends(get_chunker_orchestrator),
    embedding_orch = Depends(get_embedding_orchestrator),
    storage_orch = Depends(get_storage_orchestrator),
) -> IngestResponse:
    """Upload a file and ingest it through the full pipeline.

    The file is saved to a temporary location, processed, and deleted
    after ingestion.  Supported formats are determined by the data
    source layer (PDF, DOCX, TXT, HTML, CSV, JSON, XLSX, Markdown).
    """
    suffix = os.path.splitext(file.filename or "upload")[1]
    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
        content = await file.read()
        tmp.write(content)
        tmp_path = tmp.name

    try:
        result = await _ingest_source(
            tmp_path,
            data_source_orch=data_source_orch,
            parser_orch=parser_orch,
            chunker_orch=chunker_orch,
            embedding_orch=embedding_orch,
            storage_orch=storage_orch,
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap,
            id_equipement=id_equipement,
        )
    finally:
        os.unlink(tmp_path)

    status = "ok" if result.status == "ok" else "partial"
    return IngestResponse(
        status=status,
        results=[result],
        total_files=1,
        success_count=1 if result.status == "ok" else 0,
        error_count=1 if result.status == "error" else 0,
    )


# =====================================================================
# POST /api/v1/ingest/database — MySQL ingestion
# =====================================================================

@router.post(
    "/database",
    response_model=IngestResponse,
    summary="Ingest from MySQL",
    description="Load data from a MySQL table or custom query and run the full ingestion pipeline.",
)
async def ingest_database(
    request: IngestDatabaseRequest,
    _token: Annotated[str, Depends(verify_api_key)],
    data_source_orch = Depends(get_data_source_orchestrator),
    parser_orch = Depends(get_parser_orchestrator),
    chunker_orch = Depends(get_chunker_orchestrator),
    embedding_orch = Depends(get_embedding_orchestrator),
    storage_orch = Depends(get_storage_orchestrator),
) -> IngestResponse:
    """Ingest data from a MySQL source.

    The database connection parameters are provided in the request body.
    A custom SQL query can override the simple table-based loading.
    """
    source_config: dict = {
        "driver": request.driver,
        "host": request.host,
        "port": request.port,
        "database": request.database,
        "user": request.user,
        "password": request.password,
        "table": request.table,
    }
    if request.query:
        source_config["query"] = request.query

    result = await _ingest_source(
        source_config,
        data_source_orch=data_source_orch,
        parser_orch=parser_orch,
        chunker_orch=chunker_orch,
        embedding_orch=embedding_orch,
        storage_orch=storage_orch,
        chunk_size=request.chunk_size,
        chunk_overlap=request.chunk_overlap,
        id_equipement=request.id_equipement,
    )

    status = "ok" if result.status == "ok" else "partial"
    return IngestResponse(
        status=status,
        results=[result],
        total_files=1,
        success_count=1 if result.status == "ok" else 0,
        error_count=1 if result.status == "error" else 0,
    )


# =====================================================================
# POST /api/v1/ingest/files — Batch ingestion
# =====================================================================

@router.post(
    "/files",
    response_model=IngestResponse,
    summary="Batch ingest multiple files",
    description="Ingest multiple files from their absolute paths on the server.",
)
async def ingest_files(
    request: IngestMultipleRequest,
    _token: Annotated[str, Depends(verify_api_key)],
    data_source_orch = Depends(get_data_source_orchestrator),
    parser_orch = Depends(get_parser_orchestrator),
    chunker_orch = Depends(get_chunker_orchestrator),
    embedding_orch = Depends(get_embedding_orchestrator),
    storage_orch = Depends(get_storage_orchestrator),
) -> IngestResponse:
    """Ingest multiple files in batch.

    Each file is processed independently — a failure on one file does
    not prevent the others from being ingested.
    """
    results: list[IngestResult] = []

    for path in request.paths:
        result = await _ingest_source(
            path,
            data_source_orch=data_source_orch,
            parser_orch=parser_orch,
            chunker_orch=chunker_orch,
            embedding_orch=embedding_orch,
            storage_orch=storage_orch,
            chunk_size=request.chunk_size,
            chunk_overlap=request.chunk_overlap,
            id_equipement=request.id_equipement,
        )
        results.append(result)

    success_count = sum(1 for r in results if r.status == "ok")
    error_count = sum(1 for r in results if r.status == "error")

    if error_count == 0:
        status = "ok"
    elif success_count == 0:
        status = "error"
    else:
        status = "partial"

    return IngestResponse(
        status=status,
        results=results,
        total_files=len(results),
        success_count=success_count,
        error_count=error_count,
    )
